### ISSUE TITLE
error handling: Query does not return error

### ISSUE THREAD

**Issue by ikrammert** [chdb-io/chdb-go#2]
Hi, 
When creating a database or table, it does not return an error if it already exists, but it prints a debug on the terminal.
the example code:
```
db, err := chdb.NewSession("a") //path is option
	if err != nil {
		fmt.Println("hata", err)
		return
	}
	fmt.Print("\nburası\n")

	a := db.Query("CREATE DATABASE db")
	fmt.Println("a değeri",a)

	db.Query("USE db")
```
the terminal:
```
burası
Code: 82. DB::Exception: Database db already exists. (DATABASE_ALREADY_EXISTS)
a değeri 
```
Does anyone have any solution suggestions?
Thank you, happy new year

**Comment by auxten** [comment]
It's a known issue of chdb. See https://github.com/chdb-io/chdb/issues/54
To be fixed in chdb v1.2

**Comment by auxten** [comment]
C API supported, need adapt chdb-go to API v2
https://github.com/chdb-io/chdb/pull/105

**Comment by auxten** [comment]
Fixed. see https://github.com/chdb-io/chdb-go?tab=readme-ov-file#go-lib-example
